### ISSUE TITLE
Error al descargar.

### ISSUE THREAD

**Issue by lmorillas** [Arasaac/newapi#2]
En http://arasaac.org/descargas.php el enlace **Pictogramas en Blanco y Negro (con todas las acepciones asociadas** lleva a la url  https://arasaac.os-eu-mad-1.instantservers.telefonica.com/zonadescargas/ES_Pictogramas_ByN.jar?Signature=OEOuajpAm4ZuKN7ht3T%2FYI5vCuI%3D&Expires=11422982825&AWSAccessKeyId=cs20642893 y genera el siguiente error:
 
```
<Error>
<Code>SignatureDoesNotMatch</Code>
<Message>
The request signature we calculated does not match the signature you provided. Check your key and signing method.
</Message>
<Resource>/zonadescargas/ES_Pictogramas_ByN.jar</Resource>
<RequestId>5A8B3E58CE00C787</RequestId>
<StringToSignBytes>
47 45 54 0a 0a 0a 31 31 34 32 32 39 38 32 38 32 35 0a 2f 7a 6f 6e 61 64 65 73 63 61 72 67 61 73 2f 45 53 5f 50 69 63 74 6f 67 72 61 6d 61 73 5f 42 79 4e 2e 6a 61 72
</StringToSignBytes>
<SignatureProvided>OEOuajpAm4ZuKN7ht3T/YI5vCuI=</SignatureProvided>
<StringToSign>
GET 11422982825 /zonadescargas/ES_Pictogramas_ByN.jar
</StringToSign>
<AWSAccessKeyId>cs20642893</AWSAccessKeyId>
</Error>
```

**Comment by chemacortes** [comment]
Vale, me apunto el bug, aunque no tengo claro que sea de éste proyecto. El enlace correcto es: https://arasaac.os-eu-mad-1.instantservers.telefonica.com/zonadescargas/ES_Pictogramas_ByN.jar?Signature=lNr9mepvoU9xJ9utVhBGsuWp0MI%3D&Expires=11423062190&AWSAccessKeyId=cs20642893

Lo cambiaré el lunes.
